<?php
/**
 * This is a generated class based on the schema.org type catalog.
 *
 * @license MIT
 */


declare(strict_types=1);

namespace EFrane\SchemaObjects;

/**
 * A Report generated by governmental or non-governmental organization.
 */
class Report extends Article
{
    /**
     * The number or other unique designator assigned to a Report by the publishing
     * organization.
     */
    private $reportNumber;

    public function getReportNumber()
    {
        return $this->reportNumber;
    }

    public function setReportNumber($reportNumber)
    {
        $this->reportNumber = $reportNumber;
    }
}

